{{- define "canary-weight" }}{{ if gt .Values.img.canary 0.0 }}weight: {{.Values.img.canary}}{{ end }} {{- end }}
{{- define "canary-header" }}{{ if .Values.img.header  }}headers:{{ end }} {{- end }}
{{- define "canary-header-mode" }}{{ if .Values.img.header  }}x-mode: {{ .Values.img.header }}{{ end }} {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-img
  namespace: {{ .Release.Namespace }}
  labels:
    app: img
    version: {{ .Values.app.version }}
  annotations:
   getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-img
      prefix: /img/
      service: {{ .Release.Name }}-img
      {{include "canary-header" .}}
        {{include "canary-header-mode" .}}
      {{include "canary-weight" .}}
spec:      
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.img.port }}
  selector:
    app: {{ .Release.Name }}-img